import io.reactivex.Flowable;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        Flowable.just("Hello world").subscribe(System.out::println);
    }

}
